name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 🔄 Checkout to the branch
        uses: actions/checkout@v4

      - uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          target: 'ts,yml,json'
          language: 日本語
